[versions]
kotlin = "1.9.25"
dokka = "1.9.10"

## SDK Versions
minSdk = "24"
targetSdk = "34"
compileSdk = "34"

# Dependencies
android-gradle-plugin = "8.2.2"
gradle-versions = "0.50.0"
detekt = "1.23.3"

accompanist = "0.36.0"
androidx-activity-compose = "1.9.2"
androidx-core = "1.13.1"
androidx-lifecycle = "2.8.6"
androidx-test-junit = "1.2.1"

# update version in README when changing below
compose = "1.7.2"
# original compose version that works: 1.6.0
# https://androidx.dev/storage/compose-compiler/repository/
# https://developer.android.com/jetpack/androidx/releases/compose-compiler
composeCompiler = "1.5.15"
# original composeCompiler version that works: 1.5.8

kotlinx-coroutines = "1.7.3"
kotlinx-collections-immutable = "0.3.7"

libphonenumber = "8.13.35"

junit = "4.13.2"
robolectric = "4.11.1"
paparazzi = "1.3.1"

[libraries]
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-lifecycle-compose = {module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle"}
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-test-junit = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-test-junit" }

compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "composeCompiler" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

libphonenumber = { module = "io.michaelrocks:libphonenumber-android", version.ref = "libphonenumber" }

kotlinx-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }

junit = { module = "junit:junit", version.ref = "junit" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
roboelectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }

[plugins]
gradleVersions = { id = "com.github.ben-manes.versions", version.ref = "gradle-versions" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
paparazzi = { id = "app.cash.paparazzi", version.ref = "paparazzi" }
